# Setup
title:               Datasets of discrete objects
tagline:             'A place for your favourite datasets'
description:         'A website developed to publish and consult datasets of discrete objects'
url:                 http://localhost:4000
baseurl:             ''
# paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Antonio Montero
  url:               anteromontonio.github.io
  # email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y


collections:
  test:
    output: true
    permalink: /:collection/:path/
  chiralMaps6kE:
    output: true
    permalink: /:collection/:path/

exclude:
- phyton/*