# Setup
title:               Datasets of discrete objects
tagline:             'A place for your favourite datasets'
description:         'A website developed to publish and consult datasets of discrete objects'
url:                 https://anteromontonio.github.io
baseurl:             '/datasetsLj'
# paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Antonio Montero
  url:               anteromontonio.github.io
  # email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y


collections:
  tables:
    output: true
      permalink: /:collection/:path/
  datasets:
    output: true
      permalink: /:collection/:path
  chiralMaps6kE:
    output: true

exclude:
- phyton/*
